name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tts3:$(date +%s)

  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run Docker container
          run: |
            docker run --rm --gpus all akthangdz/tts1:latest /bin/bash -c "source .env/bin/activate && pip install --upgrade gradio && python vixtts_demo.py"
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
# docker run -it -p 5052:5052 akthangdz/tts1:latest /bin/bash -c "source .env/bin/activate && pip install --upgrade gradio && python vixtts_demo.py" --gpus all -t nvidia/cuda